sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ***
  alioss:
    access-key-id: ***
    access-key-secret: ***
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: sky-take-out-qieyi
  redis:
    host: localhost
    port: 6379
    password: 7492762870Qy@
    datebase: 0
  wechat:
    appid: wxb1fffe868d2217c3
    secret: 8f7aa4a9f4de06606c70f230d7bacae2