sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 7492762870Qy@
  alioss:
    access-key-id: LTAI5tMKtLDYph6VujnaEFno
    access-key-secret: BWVhM623cciMsSau6u2f8BPHuESOFl
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: sky-take-out-qieyi
